"""Add project bullets and tech stack

Revision ID: 1aac21955188
Revises: 921e0ed0f0a0
Create Date: 2026-09-06 02:37:24.077984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aac21955188'
down_revision: Union[str, Sequence[str], None] = '921e0ed0f0a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_bullets',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_bullets_project_id'), 'project_bullets', ['project_id'], unique=False)
    op.add_column('projects', sa.Column('tech_stack', sa.String(length=300), nullable=True))
    # Dropped without a backfill, deliberately. The descriptions held hand-written
    # bullets with inconsistent markers and hard line wrapping, so a split would have cut
    # claims in half — worse than retyping them. `docs/Project Descriptions Backup.md`
    # holds the text this destroys; the downgrade restores the column, never the rows.
    op.drop_column('projects', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'tech_stack')
    op.drop_index(op.f('ix_project_bullets_project_id'), table_name='project_bullets')
    op.drop_table('project_bullets')
    # ### end Alembic commands ###
